--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/alvin0319/CustomItemLoader
build-by-default: true
branches:
  - master
  - overwrite_item_component
projects:
  CustomItemLoader:
    path: ""
...
